[package]
name = "gptshell"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.29.0", features = ["term", "signal", "fs"] }
termion = "4.0.3"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
